Fix: Trying to make the github-actions role thhe admin of the cluster so that I can create the cluster, since it is failing to connect to the Kubernetes APi because of auth issues

diff --git a/.github/workflows/aws-infra-deploy.yml b/.github/workflows/aws-infra-deploy.yml
--- a/.github/workflows/aws-infra-deploy.yml
+++ b/.github/workflows/aws-infra-deploy.yml
@@ -28,6 +28,21 @@ jobs:
           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
           aws-region: ${{ secrets.AWS_REGION || 'eu-central-1' }}
 
+        #just a check to see if the admin secrets for the github repo are actually being used
+      - name: Verify cluster admins secret
+        run: |
+          if [ -z "$TF_VAR_cluster_admins" ]; then
+          echo "ERROR: TF_VAR_cluster_admins secret is not set"
+          exit 1
+          fi
+          echo "cluster_admins is set, proceeding..."
+        env:
+          cluster_admin_Danil: ${{secrets.cluster_admin_Danil}}
+          cluster_admin_Cejay: ${{secrets.cluster_admin_Cejay}}
+          cluster_admin_Nigel: ${{secrets.cluster_admin_Nigel}}
+          cluster_admin_Rik: ${{secrets.cluster_admin_Rik}}
+          cluster_admin_Andonis: ${{secrets.cluster_admin_Andonis}}
+  
       - name: Setup kubectl
         uses: azure/setup-kubectl@v3
         with:
